channels:
  - defaults
dependencies:
  - black >=25
  - make
  - conda-forge::pygal  # for pytest-benchmark to render SVG histograms
  - jupyter
  - notebook
  - mypy
  - numpy
  - pip
  - pip:
    - numba-scfg 
    - egglog ==12
    - pytest-benchmark >=5.2.0
